#module load make/4.3-GCCcore-10.2.0
#git clone https://github.com/gpertea/gffread
#cd gffread
#make release
#cd ../
./gffread/gffread -x ALL_COMBINED_1_MISMATCH_UNIQ_MAP.FILTER.GT3000.bam.MULTI.READ.CORR.TRANSDECODER.CDS.fa -g U.gibba.fa ALL_COMBINED_1_MISMATCH_UNIQ_MAP.FILTER.GT3000.bam.MULTI.READ.CORR.TRANSDECODER.gff3
perl fixfa.pl < ALL_COMBINED_1_MISMATCH_UNIQ_MAP.FILTER.GT3000.bam.MULTI.READ.CORR.TRANSDECODER.CDS.fa > ALL_COMBINED_1_MISMATCH_UNIQ_MAP.FILTER.GT3000.bam.MULTI.READ.CORR.TRANSDECODER.CDS.fix.fa

#CONVERED ALL_COMBINED_1_MISMATCH_UNIQ_MAP.FILTER.GT3000.bam.MULTI.READ.CORR.TRANSDECODER.CDS.fix.fa TO PROTEIN AT https://www.bioinformatics.org/sms2/translate.html